---
neutron_packages_compute:
  - neutron-openvswitch-agent
  - openvswitch-switch
  - crudini
  - sudo

rabbitmq_openstack_user: openstack
rabbitmq_openstack_password: "{{ vault_rabbitmq_openstack_password }}"

neutron_conf_path: /etc/neutron/neutron.conf
neutron_ovs_agent_conf_path: /etc/neutron/plugins/ml2/openvswitch_agent.ini

neutron_db_password: "{{ vault_neutron_db_password }}"
neutron_service_password: "{{ vault_neutron_service_password }}"
neutron_metadata_secret: "{{ vault_metadata_secret }}"

neutron_services_compute:
  - neutron-openvswitch-agent

# Sesuai network public Anda:
# provider:physical_network = provider
neutron_external_bridge: br-ex
provider_iface: ens20
neutron_bridge_mappings:
  - provider:br-ex

neutron_local_ip: "{{ management_ip }}"
neutron_tunnel_types: vxlan
neutron_l2_population: true
neutron_firewall_driver: openvswitch
