---
node_role: controller

controller_services:
  - keepalived
  - haproxy
  - mariadb
  - rabbitmq-server
  - memcached
  - apache2

keepalived_router_id: 51
keepalived_state: BACKUP
keepalived_auth_type: PASS
keepalived_auth_pass: "{{ vault_keepalived_auth_pass | default('OpenStackVIPPass') }}"
keepalived_virtual_ip: "{{ vip_internal }}"
keepalived_interface: "{{ vip_interface }}"

haproxy_global_maxconn: 4096
haproxy_stats_enabled: true
haproxy_stats_bind: "0.0.0.0:8404"
haproxy_stats_uri: /stats

# Backend awal. Beberapa service belum aktif di fase ini, jadi health check dibuat tcp.
# Nanti setelah service dipasang, backend akan mulai UP otomatis.
haproxy_openstack_services:
  - name: keystone_public
    bind_ip: "{{ vip_internal }}"
    bind_port: 5000
    backend_port: 5000
    mode: http
    check_type: tcp

  - name: glance_api
    bind_ip: "{{ vip_internal }}"
    bind_port: 9292
    backend_port: 9292
    mode: http
    check_type: tcp

  - name: placement_api
    bind_ip: "{{ vip_internal }}"
    bind_port: 8778
    backend_port: 8778
    mode: http
    check_type: tcp

  - name: nova_api
    bind_ip: "{{ vip_internal }}"
    bind_port: 8774
    backend_port: 8774
    mode: http
    check_type: tcp

  - name: neutron_api
    bind_ip: "{{ vip_internal }}"
    bind_port: 9696
    backend_port: 9696
    mode: http
    check_type: tcp

  - name: cinder_api
    bind_ip: "{{ vip_internal }}"
    bind_port: 8776
    backend_port: 8776
    mode: http
    check_type: tcp

  - name: horizon
    bind_ip: "{{ vip_internal }}"
    bind_port: 80
    backend_port: 80
    mode: http
    check_type: tcp
