---
node_role: controller

controller_services:
  - keepalived
  - haproxy
  - mariadb
  - rabbitmq-server
  - memcached
  - apache2

keepalived_router_id: 51
keepalived_state: BACKUP
keepalived_auth_type: PASS
keepalived_auth_pass: "{{ vault_keepalived_auth_pass | default('OpenStackVIPPass') }}"
keepalived_virtual_ip: "{{ vip_internal }}"
keepalived_interface: "{{ vip_interface }}"

haproxy_global_maxconn: 4096
haproxy_stats_enabled: true
haproxy_stats_bind: "0.0.0.0:8404"
haproxy_stats_uri: /stats

haproxy_openstack_services:
  - name: keystone_public
    bind_ip: "{{ vip_internal }}"
    bind_port: 5000
    backend_port: 5000
    mode: http
    httpchk:
      method: GET
      uri: /v3
      expect_status: 200

  - name: glance_api
    bind_ip: "{{ vip_internal }}"
    bind_port: 9292
    backend_port: 9292
    mode: http
    httpchk:
      method: GET
      uri: /
      expect_rstatus: "^(2|3)[0-9][0-9]$"

  - name: placement_api
    bind_ip: "{{ vip_internal }}"
    bind_port: 8778
    backend_port: 8778
    mode: http
    httpchk:
      method: GET
      uri: /
      expect_rstatus: "^(2|3)[0-9][0-9]$"

  - name: nova_api
    bind_ip: "{{ vip_internal }}"
    bind_port: 8774
    backend_port: 8774
    mode: http
    httpchk:
      method: GET
      uri: /
      expect_rstatus: "^(2|3)[0-9][0-9]$"

  - name: neutron_api
    bind_ip: "{{ vip_internal }}"
    bind_port: 9696
    backend_port: 9696
    mode: http
    httpchk:
      method: GET
      uri: /
      expect_rstatus: "^(2|3)[0-9][0-9]$"

  - name: cinder_api
    bind_ip: "{{ vip_internal }}"
    bind_port: 8776
    backend_port: 8776
    mode: http
    httpchk:
      method: GET
      uri: /
      expect_rstatus: "^(2|3)[0-9][0-9]$"

  - name: horizon
    bind_ip: "{{ vip_internal }}"
    bind_port: 80
    backend_port: 80
    mode: http
    check_type: tcp

# MariaDB Galera
mariadb_bind_address: "0.0.0.0"
mariadb_port: 3306

galera_cluster_name: openstack_galera
galera_wsrep_provider: /usr/lib/galera/libgalera_smm.so
galera_sst_method: rsync
galera_bootstrap_node: "{{ bootstrap_controller }}"
galera_cluster_nodes: "{{ groups['controllers'] }}"
galera_cluster_address: >-
  gcomm://{{ groups['controllers']
    | map('extract', hostvars, 'management_ip')
    | join(',') }}

mariadb_openstack_databases:
  - keystone
  - glance
  - placement
  - nova
  - nova_api
  - nova_cell0
  - neutron
  - cinder
  - gnocchi
  - aodh
  - masakari

# RabbitMQ Cluster
rabbitmq_cluster_name: openstack_rabbitmq
rabbitmq_bootstrap_node: "{{ groups['controllers'][0] }}"
#rabbitmq_openstack_user: openstack
rabbitmq_openstack_vhost: /
#rabbitmq_openstack_password: "{{ vault_rabbitmq_openstack_password }}"
rabbitmq_erlang_cookie: "{{ vault_rabbitmq_erlang_cookie }}"

# Memcached
memcached_port: 11211
memcached_listen_ip: "{{ management_ip }}"
memcached_memory_mb: 256
memcached_max_connections: 4096
