---
all:
  children:
    controllers:
      hosts:
        ctrl01:
          ansible_host: 172.16.2.211
          expected_hostname: controller-01
          management_ip: 172.16.2.211
          storage_ip: 172.16.1.211
          management_iface: ens19
          provider_iface: ens20
          storage_iface: eth0
          keepalived_priority: 110

        ctrl02:
          ansible_host: 172.16.2.212
          expected_hostname: controller-02
          management_ip: 172.16.2.212
          storage_ip: 172.16.1.212
          management_iface: ens19
          provider_iface: ens20
          storage_iface: eth0
          keepalived_priority: 100

        ctrl03:
          ansible_host: 172.16.2.213
          expected_hostname: controller-03
          management_ip: 172.16.2.213
          storage_ip: 172.16.1.213
          management_iface: ens19
          provider_iface: ens20
          storage_iface: eth0
          keepalived_priority: 90

    computes:
      hosts:
        cmp01:
          ansible_host: 172.16.2.221
          expected_hostname: compute-01
          management_ip: 172.16.2.221
          storage_ip: 172.16.1.221
          management_iface: ens19
          provider_iface: ens20
          storage_iface: eth0

        cmp02:
          ansible_host: 172.16.2.222
          expected_hostname: compute-02
          management_ip: 172.16.2.222
          storage_ip: 172.16.1.222
          management_iface: ens19
          provider_iface: ens20
          storage_iface: eth0

    openstack:
      children:
        controllers:
        computes:

    network:
      children:
        openstack:

    ceph_clients:
      children:
        openstack:
