---
- name: Phase 04 - HA VIP and HAProxy baseline
  hosts: controllers
  become: true
  gather_facts: true

  pre_tasks:
    - name: Force load lab group vars
      ansible.builtin.include_vars:
        file: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/../inventories/lab-5node/group_vars/all.yml"
        - "{{ playbook_dir }}/../inventories/lab-5node/group_vars/network.yml"
        - "{{ playbook_dir }}/../inventories/lab-5node/group_vars/openstack.yml"
        - "{{ playbook_dir }}/../inventories/lab-5node/group_vars/controllers.yml"
#        - "{{ playbook_dir }}/../inventories/lab-5node/group_vars/haproxy_services.yml"
        - "{{ playbook_dir }}/../inventories/lab-5node/group_vars/vault.yml"

    - name: Debug HAProxy service variables before role
      ansible.builtin.debug:
        msg:
          - "inventory_hostname={{ inventory_hostname }}"
          - "groups={{ group_names }}"
          - "haproxy_openstack_services_defined={{ haproxy_openstack_services is defined }}"
          - "haproxy_openstack_services_count={{ haproxy_openstack_services | default([]) | length }}"

    - name: Assert HAProxy service variables before role
      ansible.builtin.assert:
        that:
          - haproxy_openstack_services is defined
          - haproxy_openstack_services | length > 0
        fail_msg: "haproxy_openstack_services belum terbaca sebelum role ha/haproxy."

  roles:
    - role: ha/keepalived
    - role: ha/haproxy

  post_tasks:
    - name: Validate keepalived service is active
      ansible.builtin.command: systemctl is-active keepalived
      changed_when: false

    - name: Validate haproxy service is active
      ansible.builtin.command: systemctl is-active haproxy
      changed_when: false

    - name: Validate HAProxy configuration
      ansible.builtin.command: haproxy -c -f /etc/haproxy/haproxy.cfg
      changed_when: false

    - name: Check VIP status on controllers
      ansible.builtin.shell: "ip -4 addr show {{ vip_interface }} | grep -F '{{ vip_internal }}' || true"
      register: vip_check
      changed_when: false

    - name: Print VIP status
      ansible.builtin.debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "VIP interface: {{ vip_interface }}"
          - "VIP: {{ vip_internal }}"
          - "VIP check: {{ vip_check.stdout | default('not-present-on-this-node') }}"

    - name: Print HA phase summary
      ansible.builtin.debug:
        msg:
          - "HA phase completed on {{ inventory_hostname }}"
          - "Keepalived VIP: {{ vip_internal }} on {{ vip_interface }}"
          - "HAProxy installed and validated"
